Updated bootstrap to check if homebrew is available  and install if not,  and updated to Clean yarn/npm before installing
Updated bootstrap to check if homebrew is available  and install if not,  and updated to Clean yarn/npm before installing
🙏

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -3,7 +3,6 @@
 set -e
 
 cd "$(dirname "$0")/.."
-
 if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ] && [ "$SKIP_BREW" != "1" ]; then
   brew bundle check >/dev/null 2>&1 || {
     echo "==> Installing Homebrew dependencies…"
@@ -11,8 +10,26 @@ if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ] && [ "$SKIP_BREW" != "1" ];
   }
 fi
 
-echo "==> Installing Node dependencies…"
+# Check Node version
+INSTALLED_NODE_VERSION=$(node -v)
+if [ -z "$INSTALLED_NODE_VERSION" ]; then
+  echo "Node.js is not installed. Please install it"
+  exit 1
+elif [ "$(printf '$INSTALLED_NODE_VERSION\n$REQUIRED_NODE_VERSION' | sort -V | head -n1)" != "$REQUIRED_NODE_VERSION" ]; then
+  echo "Node.js version $REQUIRED_NODE_VERSION or greater is required. Found: $INSTALLED_NODE_VERSION"
+  exit 1
+fi
 
+# Clean npm/yarn cache before installing
+echo "==> Clearing npm/yarn cache..."
+$PACKAGE_MANAGER cache clean --force
+
+# Install dependencies
+echo "==> Installing Node dependencies…"
 PACKAGE_MANAGER=$(command -v yarn >/dev/null 2>&1 && echo "yarn" || echo "npm")
 
 $PACKAGE_MANAGER install
+
+# Optionally run tests
+echo "==> Running tests..."
+$PACKAGE_MANAGER run test
